### ISSUE TITLE
Sha mismatch

### ISSUE THREAD

**Issue by S3RK** [in2pire/homebrew-pinba#1]
I try to install pinba engine from brew using `brew install mysql-engine-pinba` and get error

Output:

```
==> Installing mysql-engine-pinba from in2pire/homebrew-pinba
==> Downloading http://pinba.org/files/pinba_engine-1.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-engine-pinba-1.0.0.tar.gz
==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.23.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-engine-pinba--mysql-5.6.23.tar.gz
==> /usr/local/bin/cmake -DBUILD_CONFIG=mysql_release -Wno-dev && cd include && make
==> Downloading https://github.com/tony2001/pinba_engine/archive/master.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-engine-pinba--master-1.0.0.tar.gz
Error: SHA1 mismatch
Expected: 07f5640339e96487630b0617a7283b6f28c7697c
Actual: 7d1dcf32906a0e5d735278715dc25fdff560e3de
Archive: /Library/Caches/Homebrew/mysql-engine-pinba--master-1.0.0.tar.gz
```

It's strange that brew downloaded two version of engine `mysql-engine-pinba-1.0.0.tar.gz` and `mysql-engine-pinba--master-1.0.0.tar.gz`. But anyway sha1 of both files are different form expected one.

**Comment by nhatthm** [comment]
Hi, I've found a problem while compiling new pinba version https://github.com/tony2001/pinba_engine/issues/40
I'll fix and double check after he fixes it

**Comment by nhatthm** [comment]
Hi, I've just fixed the issue but only tested with percona server. Could you please help me to test again with MySQL?

**Comment by nhatthm** [comment]
I've just tested with mysql, it's good. Tell me if you still have this problem

**Comment by S3RK** [comment]
Thx, it works now :+1:

**Comment by Lazur** [comment]
Hi. Problem still actual for me. Have same error.
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.24.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-engine-pinba--mysql-5.6.24.tar.gz
==> /usr/local/bin/cmake -DBUILD_CONFIG=mysql_release -Wno-dev && cd include && make
==> Downloading https://github.com/tony2001/pinba_engine/archive/master.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-engine-pinba--master-1.1.0.tar.gz
Error: SHA1 mismatch
Expected: 7d1dcf32906a0e5d735278715dc25fdff560e3de
Actual: 592eb7cc76044df448ad8cc5fbe3022ef908a75b
Archive: /Library/Caches/Homebrew/mysql-engine-pinba--master-1.1.0.tar.gz
To retry an incomplete download, remove the file above.
I try to remove and run command again, no effect...

**Comment by nhatthm** [comment]
Hi Lazur, thanks for reporting. Probably Pinba's author made some changes in master branch and it  caused hash mismatch. I've just fixed it

**Comment by Lazur** [comment]
Hi casterx, problem stil active with archive
==> Downloading from https://codeload.github.com/tony2001/pinba_engine/tar.gz/master
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 7d1dcf32906a0e5d735278715dc25fdff560e3de
Actual: 592eb7cc76044df448ad8cc5fbe3022ef908a75b
Archive: /Library/Caches/Homebrew/mysql-engine-pinba--master-1.1.0.tar.gz
Thank you.

**Comment by nhatthm** [comment]
Hi, did you run `brew update && brew upgrade`?  I already changed the hash in https://github.com/in2pire/homebrew-pinba/blob/master/Formula/mysql-engine-pinba.rb

**Comment by Lazur** [comment]
Hello. Yes, i try brew update few days ago, It is works. thx
